schema: './src/server/schema/schema.graphql'
documents: './src/client/**/*.ts'

extensions:
  codegen:
    ignoreNoDocuments: true
    emitLegacyCommonJSImports: false

    generates:
      './src/client/gql/':
        preset: 'client'

      './src/server/schema/schema.types.ts':
        plugins: ['typescript', 'typescript-resolvers']

        config:
          immutableTypes: true
