schema: './src/server/schema/schema.graphql'
documents:
  - './src/cli/**/*.{ts,tsx}'
  - './src/client/**/*.{ts,tsx}'
  - './tests/**/*.{ts,tsx}'

extensions:
  codegen:
    ignoreNoDocuments: true
    emitLegacyCommonJSImports: false

    generates:
      './src/cli/gql/':
        preset: 'client'
        documents:
          - '!./src/client/**/*.{ts,tsx}'
          - '!./tests/**/*.{ts,tsx}'

        presetConfig:
          fragmentMasking:
            unmaskFunctionName: 'unmask'

      './src/client/gql/':
        preset: 'client'
        documents:
          - '!./src/cli/**/*.{ts,tsx}'
          - '!./tests/**/*.{ts,tsx}'

        presetConfig:
          fragmentMasking:
            unmaskFunctionName: 'unmask'

      './tests/gql/':
        preset: 'client'
        documents:
          - '!./src/cli/**/*.{ts,tsx}'
          - '!./src/client/**/*.{ts,tsx}'

        presetConfig:
          fragmentMasking:
            unmaskFunctionName: 'unmask'

      './src/server/schema/schema.types.ts':
        plugins: ['typescript', 'typescript-resolvers']

        config:
          immutableTypes: true
